server:
  port: 8000

spring:
  application:
    name:personal-finanace-tracker-api

  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: finance_user
    passoword: finance_pass123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-auto
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    com.financetracker: DEBUG
    com.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  
  endpoint:
    health:
      show-detils: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html  

  